repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: [ "--config=.flake8" ]
        additional_dependencies: [ 'flake8-bugbear==23.9.16' ]

  # removes unused imports and unused variables
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake