name: green.ai
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.11.0
  - ipykernel
  - codecarbon
  - conda-forge::tqdm
  - conda-forge::transformers
  - huggingface_hub
  - datasets==2.16.1
  - matplotlib
  - anaconda::ipywidgets
  - flake8
  - pre-commit
  - conda-forge::pydantic
  - tqdm
  - pip:
      - vllm
      - polars
      - pytest
      - pytest-asyncio
      - mistral_common
      - spacy
      - scikit-learn
      - sentence-transformers